name: "Cache Dependencies"

description: "Setup Python with pip Cache and Install Dependencies"

inputs:
  dependencies-directory:
    description: Where to search for requirements files.
    required: false
    default: "."
    type: string

  deploy-keys:
    description: Packages deploy keys.
    required: false
    default: ""
    type: string

  python-version:
    description: What python version to use.
    required: false
    default: "3.10"
    type: string

  application:
    description: Whether to install application dependencies.
    required: false
    default: false
    type: boolean

  application-packages:
    description: Project packages to install with pip.
    required: false
    default: ""
    type: string

  quality:
    description: Whether to install quality assurance dependencies.
    required: false
    default: false
    type: boolean

  quality-packages:
    description: Override packages to install with pip.
    required: false
    default: "isort black mypy flake8 pylint"
    type: string

  security:
    description: Whether to install security dependencies.
    required: false
    default: false
    type: boolean

  security-packages:
    description: Override packages to install with pip.
    required: false
    default: "bandit"
    type: string

  test:
    description: Whether to install test dependencies.
    required: false
    default: false
    type: boolean

  test-packages:
    description: Override packages to install with pip.
    required: false
    default: "pytest pytest-cov requests"
    type: string

defaults:
  shell: bash
  working-directory: ${{ inputs.dependencies-directory }}

runs:
  using: "composite"
  steps:
    - name: Output Config
      run: |
        echo "Install Application: ${{ inputs.application }}"
        echo "Install Quality: ${{ inputs.quality }}"
        echo "Install Security: ${{ inputs.security }}"
        echo "Install Test: ${{ inputs.test }}"
      shell: bash

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Deploy Keys
      uses: CristovamSilva/ssh-agent-action@master
      with:
        ssh-private-key: ${{ inputs.deploy-keys }}

    - name: Setup Python and Pip Cache
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          **/requirements*.txt
          **/setup.py
          **/pyproject.toml
          **/setup.cfg

    - name: Install Python Dependencies
      run: python -m pip install --upgrade pip pipenv setuptools wheel

    - name: Install Application Dependencies
      if: inputs.application == 'true'
      run: |
        if [ -z "${{ inputs.application-packages }}" ]; then
            echo "No application packages to install"
        else
            pip install ${{ inputs.application-packages }}
        fi
        if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi
      shell: bash
      working-directory: ${{ inputs.dependencies-directory }}

    - name: Install QA Dependencies
      if: inputs.quality  == 'true'
      run: |
        pip install --upgrade ${{ inputs.quality-packages }}
        if [ -f ./requirements-qa.txt ]; then pip install -r ./requirements-qa.txt; fi
      shell: bash
      working-directory: ${{ inputs.dependencies-directory }}

    - name: Install Security Dependencies
      if: inputs.security  == 'true'
      run: |
        pip install --upgrade ${{ inputs.security-packages }}
        if [ -f ./requirements-sec.txt ]; then pip install -r ./requirements-sec.txt; fi
      shell: bash
      working-directory: ${{ inputs.dependencies-directory }}

    - name: Install Test Dependencies
      if: inputs.test  == 'true'
      run: |
        pip install --upgrade ${{ inputs.test-packages }}
        if [ -f ./requirements-test.txt ]; then pip install -r ./requirements-test.txt; fi
      shell: bash
      working-directory: ${{ inputs.dependencies-directory }}
